# encoding: utf-8
# vim: ft=ruby expandtab shiftwidth=2 tabstop=2

#
# WordPress Default Theme
# Theme's slug or url to the theme's .zip.
#
theme: 'https://github.com/ito-artsfarm/itoartsfarm2016-wp/archive/master.zip'
